apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "cdg.nomComplet" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cdg.etiquettes" . | nindent 4 }}
spec:
  hard:
    {{- toYaml .Values.espaceDeNoms.quota | nindent 4 }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "cdg.nomComplet" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cdg.etiquettes" . | nindent 4 }}
spec:
  limits:
    - type: Container
      default:
        {{- toYaml .Values.espaceDeNoms.limitesParDefaut.defaut | nindent 8 }}
      defaultRequest:
        {{- toYaml .Values.espaceDeNoms.limitesParDefaut.requeteParDefaut | nindent 8 }}
      max:
        {{- toYaml .Values.espaceDeNoms.limitesParDefaut.max | nindent 8 }}
