apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cdg.nomComplet" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cdg.etiquettes" . | nindent 4 }}
# aucun droit sur l'API de Kubernetes (aucun Role ni RoleBinding) et aucun jeton monté
automountServiceAccountToken: false
